allowBuilds:
  core-js: true
  esbuild: true
pmOnFail: error
blockExoticSubdeps: true
ignorePatchFailures: false
minimumReleaseAge: 4320
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - ua-parser-js@1.0.41
overrides:
  '@arethetypeswrong/core@0.18.1>fflate': 0.8.2
patchedDependencies:
  '@changesets/cli@2.31.0': patches/@changesets__cli@2.31.0.patch
